# Generated by Django 5.2.1 on 2025-05-18 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('is_entrepreneur', 'Can create projects'), ('is_investor', 'Can invest in projects'), ('is_admin', 'Can manage the platform'))},
        ),
    ]
