# Generated by Django 5.2.1 on 2025-05-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='current_amount',
        ),
    ]
